//! LLVM IR code generation (textual IR).
//!
//! Numbers and Booleans are kept unboxed in SSA registers / stack slots; every other value is
//! a pointer to a boxed runtime value managed by `l2-native-rt` (null = `Null`). See the
//! ownership protocol documented in `l2-native-rt`. Exceptions use a pending flag that is
//! checked after each call that may throw; the code then branches to the innermost landing
//! block (catch dispatch, finally, scope drops, or the function's exceptional exit).

use crate::hir::*;
use crate::types::*;
use l2_runtime::ops::{ArithOp, CmpOp};
use l2_runtime::{Builtin, ExcKind, FloatTy, IntTy};
use std::collections::{BTreeSet, HashMap};
use std::fmt::Write as _;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Repr {
    I1,
    I8,
    I16,
    I32,
    I64,
    F32,
    F64,
    Ptr,
    Void,
}

impl Repr {
    fn ll(self) -> &'static str {
        match self {
            Repr::I1 => "i1",
            Repr::I8 => "i8",
            Repr::I16 => "i16",
            Repr::I32 => "i32",
            Repr::I64 => "i64",
            Repr::F32 => "float",
            Repr::F64 => "double",
            Repr::Ptr => "ptr",
            Repr::Void => "void",
        }
    }
    fn zero(self) -> &'static str {
        match self {
            Repr::Ptr => "null",
            Repr::F32 | Repr::F64 => "0.0",
            Repr::I1 => "false",
            _ => "0",
        }
    }
    fn is_int(self) -> bool {
        matches!(self, Repr::I1 | Repr::I8 | Repr::I16 | Repr::I32 | Repr::I64)
    }
}

pub fn repr(t: &Type) -> Repr {
    match t {
        Type::Bool => Repr::I1,
        Type::Int(i) => match i.bits() {
            8 => Repr::I8,
            16 => Repr::I16,
            32 => Repr::I32,
            _ => Repr::I64,
        },
        Type::Float(FloatTy::F64) => Repr::F64,
        Type::Float(_) => Repr::F32,
        Type::Void | Type::Never | Type::Error => Repr::Void,
        Type::Ref(false, t) => repr(t),
        _ => Repr::Ptr,
    }
}

/// Parameter/return attribute text for a repr (i1 is passed zero-extended for C interop).
fn attr(r: Repr) -> &'static str {
    if r == Repr::I1 {
        "zeroext "
    } else {
        ""
    }
}

#[derive(Clone, Debug)]
struct V {
    r: Repr,
    v: String,
    owned: bool,
}

impl V {
    fn new(r: Repr, v: impl Into<String>, owned: bool) -> V {
        V { r, v: v.into(), owned }
    }
    fn void() -> V {
        V::new(Repr::Void, "", false)
    }
    fn typed(&self) -> String {
        format!("{} {}", self.r.ll(), self.v)
    }
}

pub struct TargetInfo {
    pub triple: String,
}

pub fn triple_for(t: Target) -> String {
    let os = std::env::consts::OS;
    match (t, os) {
        (Target::Amd64, "windows") => "x86_64-pc-windows-msvc",
        (Target::I386, "windows") => "i686-pc-windows-msvc",
        (Target::Arm64, "windows") => "aarch64-pc-windows-msvc",
        (Target::Amd64, "macos") => "x86_64-apple-darwin",
        (Target::Arm64, "macos") => "aarch64-apple-darwin",
        (Target::I386, "macos") => "i686-apple-darwin",
        (Target::Amd64, _) => "x86_64-unknown-linux-gnu",
        (Target::I386, _) => "i686-unknown-linux-gnu",
        (Target::Arm64, _) => "aarch64-unknown-linux-gnu",
    }
    .to_string()
}

struct ModGen<'p> {
    p: &'p Program,
    strings: HashMap<Vec<u8>, String>,
    globals: String,
    intrinsics: BTreeSet<String>,
    closure_wrappers: BTreeSet<FuncId>,
    lists: Vec<Vec<ClassId>>,
}

/// Generates a complete LLVM module for the program.
pub fn emit_module(p: &Program, target: Target) -> String {
    let mut m = ModGen { p, strings: HashMap::new(), globals: String::new(), intrinsics: BTreeSet::new(), closure_wrappers: BTreeSet::new(), lists: Vec::new() };
    let mut funcs = String::new();
    for (i, f) in p.funcs.iter().enumerate() {
        funcs.push_str(&FnGen::generate(&mut m, i as FuncId, f));
    }
    for (sid, _) in p.selectors.iter().enumerate() {
        funcs.push_str(&m.dispatcher(sid as SelectorId));
    }
    let wrappers: Vec<FuncId> = m.closure_wrappers.iter().copied().collect();
    for f in wrappers {
        funcs.push_str(&m.closure_wrapper(f));
    }
    funcs.push_str(&m.main_fn());
    let class_table = m.class_table();
    let mut out = String::new();
    let _ = writeln!(out, "; generated by {} {}", crate::LANG_NAME, env!("CARGO_PKG_VERSION"));
    let _ = writeln!(out, "target triple = \"{}\"\n", triple_for(target));
    out.push_str(RUNTIME_DECLS);
    for i in &m.intrinsics {
        let _ = writeln!(out, "{}", i);
    }
    out.push('\n');
    let _ = writeln!(out, "@l2_depth = internal global i32 0");
    for (i, _) in p.globals.iter().enumerate() {
        let _ = writeln!(out, "@g.{} = internal global ptr null", i);
    }
    out.push_str(&class_table);
    for (i, l) in m.lists.iter().enumerate() {
        let items: Vec<String> = l.iter().map(|c| format!("i32 {}", c)).collect();
        let _ = writeln!(out, "@cl.{} = private constant [{} x i32] [{}]", i, l.len(), items.join(", "));
    }
    out.push_str(&m.globals);
    out.push('\n');
    out.push_str(&funcs);
    out
}

const RUNTIME_DECLS: &str = r#"@L2_PENDING = external global i8
declare void @l2_rt_init(ptr, i32, ptr, i32, i32, ptr)
declare ptr @l2_args()
declare i32 @l2_rt_finish(i32)
declare ptr @l2_box_int(i8, i64)
declare ptr @l2_box_f64(i8, double)
declare ptr @l2_box_bool(i1 zeroext)
declare i64 @l2_unbox_int(ptr)
declare double @l2_unbox_f64(ptr)
declare zeroext i1 @l2_unbox_bool(ptr)
declare ptr @l2_str_lit(ptr, i64)
declare ptr @l2_big_lit(ptr, i64)
declare ptr @l2_dup(ptr)
declare void @l2_free(ptr)
declare float @l2_round_f16(float)
declare ptr @l2_cell_new(ptr)
declare ptr @l2_ref_get(ptr)
declare ptr @l2_ref_take(ptr)
declare void @l2_ref_set(ptr, ptr)
declare ptr @l2_field_ref(ptr, i32)
declare ptr @l2_new_object(i32)
declare i32 @l2_class_of(ptr)
declare ptr @l2_get_field(ptr, i32)
declare i64 @l2_get_field_int(ptr, i32)
declare double @l2_get_field_f64(ptr, i32)
declare zeroext i1 @l2_get_field_bool(ptr, i32)
declare void @l2_set_field(ptr, i32, ptr)
declare void @l2_set_field_int(ptr, i32, i8, i64)
declare void @l2_set_field_f64(ptr, i32, i8, double)
declare void @l2_set_field_bool(ptr, i32, i1 zeroext)
declare ptr @l2_make_tuple(ptr, i32)
declare ptr @l2_tuple_get(ptr, i32)
declare ptr @l2_make_dict(ptr, i32)
declare ptr @l2_closure_new(ptr, ptr, i32)
declare ptr @l2_closure_fn(ptr)
declare ptr @l2_closure_cap(ptr, i32)
declare ptr @l2_sb_new()
declare void @l2_sb_push_box(ptr, ptr)
declare void @l2_sb_push_lit(ptr, ptr, i64)
declare void @l2_sb_push_int(ptr, i8, i64)
declare void @l2_sb_push_f64(ptr, i8, double)
declare void @l2_sb_push_bool(ptr, i1 zeroext)
declare ptr @l2_sb_finish(ptr)
declare ptr @l2_arith(i8, ptr, ptr, i1 zeroext)
declare ptr @l2_negate(ptr, i1 zeroext)
declare ptr @l2_bitnot(ptr)
declare zeroext i1 @l2_compare(i8, ptr, ptr)
declare i64 @l2_pow_int(i8, i64, i64, i1 zeroext)
declare void @l2_throw_overflow(i8, i8)
declare void @l2_throw_div_zero(i1 zeroext)
declare void @l2_throw_stack_overflow()
declare ptr @l2_convert(ptr, ptr)
declare ptr @l2_cast(ptr, ptr, i1 zeroext)
declare void @l2_nonnull(ptr, i1 zeroext)
declare void @l2_throw(ptr)
declare ptr @l2_take_pending()
declare void @l2_set_pending(ptr)
declare zeroext i1 @l2_exc_matches(ptr, ptr, i32)
declare ptr @l2_builtin(i16, ptr, i32)
declare ptr @l2_builtin_mut_slot(i16, ptr, ptr, i32)
declare ptr @l2_builtin_mut_ref(i16, ptr, ptr, i32)
declare void @l2_drop_value(ptr)
declare void @l2_free_manual(ptr)
"#;

fn esc_bytes(b: &[u8]) -> String {
    let mut s = String::new();
    for &c in b {
        if (0x20..0x7f).contains(&c) && c != b'"' && c != b'\\' {
            s.push(c as char);
        } else {
            let _ = write!(s, "\\{:02X}", c);
        }
    }
    s
}

fn float_lit(v: f64, r: Repr) -> String {
    let v = if r == Repr::F32 { v as f32 as f64 } else { v };
    format!("0x{:016X}", v.to_bits())
}

fn int_kind(t: &Type) -> IntTy {
    match t.deref() {
        Type::Int(i) => *i,
        _ => IntTy::I64,
    }
}

fn float_kind(t: &Type) -> FloatTy {
    match t.deref() {
        Type::Float(f) => *f,
        _ => FloatTy::F64,
    }
}

impl<'p> ModGen<'p> {
    /// Returns the global name of a NUL-terminated string constant.
    fn cstr(&mut self, s: &str) -> String {
        let mut b = s.as_bytes().to_vec();
        b.push(0);
        if let Some(n) = self.strings.get(&b) {
            return n.clone();
        }
        let name = format!("@s.{}", self.strings.len());
        let _ = writeln!(self.globals, "{} = private unnamed_addr constant [{} x i8] c\"{}\"", name, b.len(), esc_bytes(&b));
        self.strings.insert(b, name.clone());
        name
    }

    fn list(&mut self, l: &[ClassId]) -> String {
        if let Some(i) = self.lists.iter().position(|x| x == l) {
            return format!("@cl.{}", i);
        }
        self.lists.push(l.to_vec());
        format!("@cl.{}", self.lists.len() - 1)
    }

    fn sig(&self, f: FuncId) -> (Vec<Repr>, Repr) {
        let func = &self.p.funcs[f as usize];
        let ps = func.params.iter().map(|p| repr(&func.locals[*p as usize].ty)).collect();
        (ps, repr(&func.ret))
    }

    fn class_table(&mut self) -> String {
        let p = self.p;
        let mut out = String::new();
        out.push_str("%ClassDesc = type { i32, ptr, i32, ptr, ptr, i32, ptr, ptr, ptr, ptr, ptr, i32 }\n");
        let mut entries = Vec::new();
        for (i, c) in p.classes.iter().enumerate() {
            let name = self.cstr(&c.name);
            let nf = c.fields.len();
            let (fnames, fnull) = if nf == 0 {
                ("null".to_string(), "null".to_string())
            } else {
                let names: Vec<String> = c.fields.iter().map(|f| format!("ptr {}", self.cstr(&f.name))).collect();
                let _ = writeln!(out, "@cf.{} = private constant [{} x ptr] [{}]", i, nf, names.join(", "));
                let nulls: Vec<String> = c.fields.iter().map(|f| format!("i8 {}", if f.ty.is_nullable() { 1 } else { 0 })).collect();
                let _ = writeln!(out, "@cn.{} = private constant [{} x i8] [{}]", i, nf, nulls.join(", "));
                (format!("@cf.{}", i), format!("@cn.{}", i))
            };
            let ifs = if c.ifaces.is_empty() {
                "null".to_string()
            } else {
                let items: Vec<String> = c.ifaces.iter().map(|x| format!("i32 {}", x)).collect();
                let _ = writeln!(out, "@ci.{} = private constant [{} x i32] [{}]", i, c.ifaces.len(), items.join(", "));
                format!("@ci.{}", i)
            };
            let f = |x: Option<FuncId>| x.map(|f| format!("@f.{}", f)).unwrap_or("null".into());
            entries.push(format!(
                "%ClassDesc {{ i32 {}, ptr {}, i32 {}, ptr {}, ptr {}, i32 {}, ptr {}, ptr {}, ptr {}, ptr {}, ptr {}, i32 {} }}",
                c.parent.map(|x| x as i64).unwrap_or(-1),
                name,
                nf,
                fnames,
                fnull,
                if c.is_throwable { 1 } else { 0 },
                f(c.to_string_fn),
                f(c.equals_fn),
                f(c.compare_fn),
                f(c.drop_fn),
                ifs,
                c.ifaces.len()
            ));
        }
        let _ = writeln!(out, "@l2.classes = private constant [{} x %ClassDesc] [\n  {}\n]", entries.len(), entries.join(",\n  "));
        let exc: Vec<String> = ExcKind::ALL.iter().map(|k| format!("i32 {}", p.exc_class(*k))).collect();
        let _ = writeln!(out, "@l2.exc = private constant [{} x i32] [{}]", exc.len(), exc.join(", "));
        out
    }

    fn dispatcher(&mut self, sid: SelectorId) -> String {
        let p = self.p;
        let sel = &p.selectors[sid as usize];
        let ret = repr(&sel.ret);
        let mut params = vec![Repr::Ptr];
        params.extend(sel.params.iter().map(repr));
        let plist: Vec<String> = params.iter().enumerate().map(|(i, r)| format!("{}{} %a{}", r.ll(), if *r == Repr::I1 { " zeroext" } else { "" }, i)).collect();
        let mut s = String::new();
        let _ = writeln!(s, "define internal {}{} @sel.{}({}) {{", attr(ret), ret.ll(), sid, plist.join(", "));
        let _ = writeln!(s, "entry:\n  %c = call i32 @l2_class_of(ptr %a0)");
        let impls: Vec<(usize, FuncId)> = p.classes.iter().enumerate().filter_map(|(i, c)| c.vtable.get(&sid).map(|f| (i, *f))).collect();
        let cases: Vec<String> = impls.iter().map(|(c, _)| format!("i32 {}, label %c{}", c, c)).collect();
        let _ = writeln!(s, "  switch i32 %c, label %fail [ {} ]", cases.join(" "));
        let args: Vec<String> = params.iter().enumerate().map(|(i, r)| format!("{}{} %a{}", r.ll(), if *r == Repr::I1 { " zeroext" } else { "" }, i)).collect();
        for (c, f) in &impls {
            let _ = writeln!(s, "c{}:", c);
            if ret == Repr::Void {
                let _ = writeln!(s, "  call void @f.{}({})\n  ret void", f, args.join(", "));
            } else {
                let _ = writeln!(s, "  %r{} = call {}{} @f.{}({})\n  ret {} %r{}", c, attr(ret), ret.ll(), f, args.join(", "), ret.ll(), c);
            }
        }
        let _ = writeln!(s, "fail:");
        for (i, r) in params.iter().enumerate() {
            if *r == Repr::Ptr {
                let _ = writeln!(s, "  call void @l2_free(ptr %a{})", i);
            }
        }
        if ret == Repr::Void {
            let _ = writeln!(s, "  ret void\n}}\n");
        } else {
            let _ = writeln!(s, "  ret {} {}\n}}\n", ret.ll(), ret.zero());
        }
        s
    }

    fn closure_wrapper(&mut self, f: FuncId) -> String {
        let (ps, ret) = self.sig(f);
        let plist: Vec<String> = ps.iter().enumerate().map(|(i, r)| format!("{}{} %a{}", r.ll(), if *r == Repr::I1 { " zeroext" } else { "" }, i)).collect();
        let mut s = String::new();
        let mut all = vec!["ptr %env".to_string()];
        all.extend(plist.clone());
        let _ = writeln!(s, "define internal {}{} @f.{}.clo({}) {{\nentry:", attr(ret), ret.ll(), f, all.join(", "));
        if ret == Repr::Void {
            let _ = writeln!(s, "  call void @f.{}({})\n  ret void\n}}\n", f, plist.join(", "));
        } else {
            let _ = writeln!(s, "  %r = call {}{} @f.{}({})\n  ret {} %r\n}}\n", attr(ret), ret.ll(), f, plist.join(", "), ret.ll());
        }
        s
    }

    fn main_fn(&mut self) -> String {
        let p = self.p;
        let mut s = String::new();
        let _ = writeln!(s, "define i32 @main(i32 %argc, ptr %argv) {{\nentry:");
        let _ = writeln!(s, "  call void @l2_rt_init(ptr @l2.classes, i32 {}, ptr @l2.exc, i32 {}, i32 %argc, ptr %argv)", p.classes.len(), ExcKind::ALL.len());
        for i in 0..p.globals.len() {
            let _ = writeln!(s, "  %g{} = call ptr @l2_cell_new(ptr null)\n  store ptr %g{}, ptr @g.{}", i, i, i);
        }
        let _ = writeln!(s, "  call void @f.{}()", p.init);
        let _ = writeln!(s, "  %p0 = load i8, ptr @L2_PENDING\n  %e0 = icmp ne i8 %p0, 0\n  br i1 %e0, label %fin, label %run");
        let _ = writeln!(s, "run:");
        let main_ret = repr(&p.funcs[p.main as usize].ret);
        let arg = if p.main_takes_args {
            let _ = writeln!(s, "  %args = call ptr @l2_args()");
            "ptr %args"
        } else {
            ""
        };
        let code = if main_ret == Repr::Void {
            let _ = writeln!(s, "  call void @f.{}({})", p.main, arg);
            "0".to_string()
        } else {
            let _ = writeln!(s, "  %rc = call {} @f.{}({})", main_ret.ll(), p.main, arg);
            "%rc".to_string()
        };
        let _ = writeln!(s, "  br label %fin\nfin:\n  %code = phi i32 [ 0, %entry ], [ {}, %run ]", code);
        let _ = writeln!(s, "  %r = call i32 @l2_rt_finish(i32 %code)\n  ret i32 %r\n}}");
        s
    }
}

// =============================================================================================
// functions

enum Clean<'h> {
    Finally { body: &'h [Stmt], landing_depth: usize },
    Drops { locals: Vec<LocalId>, landing_depth: usize },
}

struct Brk {
    is_loop: bool,
    break_lbl: String,
    cont_lbl: String,
    depth: usize,
}

struct FnGen<'m, 'p, 'h> {
    m: &'m mut ModGen<'p>,
    f: &'h Func,
    allocas: Vec<String>,
    body: Vec<String>,
    tmp: u32,
    lbl: u32,
    slots: Vec<String>,
    reprs: Vec<Repr>,
    terminated: bool,
    cur_label: String,
    cleanups: Vec<Clean<'h>>,
    landings: Vec<String>,
    brks: Vec<Brk>,
    ret_repr: Repr,
    ownership: bool,
}

impl<'m, 'p, 'h> FnGen<'m, 'p, 'h> {
    fn generate(m: &'m mut ModGen<'p>, fid: FuncId, f: &'h Func) -> String {
        let ownership = m.p.config.memory == MemoryMode::Ownership;
        let mut g = FnGen {
            m,
            f,
            allocas: Vec::new(),
            body: Vec::new(),
            tmp: 0,
            lbl: 0,
            slots: Vec::new(),
            reprs: Vec::new(),
            terminated: false,
            cur_label: "body".into(),
            cleanups: Vec::new(),
            landings: Vec::new(),
            brks: Vec::new(),
            ret_repr: repr(&f.ret),
            ownership,
        };
        for (i, l) in f.locals.iter().enumerate() {
            let r = if l.cell { Repr::Ptr } else { repr(&l.ty) };
            let r = if r == Repr::Void { Repr::Ptr } else { r };
            g.slots.push(format!("%l{}", i));
            g.reprs.push(r);
            g.allocas.push(format!("  %l{} = alloca {}", i, r.ll()));
            if r == Repr::Ptr {
                g.allocas.push(format!("  store ptr null, ptr %l{}", i));
            }
        }
        if g.ret_repr != Repr::Void {
            g.allocas.push(format!("  %retval = alloca {}", g.ret_repr.ll()));
        }
        // parameters
        let mut params = Vec::new();
        if f.kind == FuncKind::Lambda {
            params.push("ptr %env".to_string());
        }
        for (i, pid) in f.params.iter().enumerate() {
            let r = repr(&f.locals[*pid as usize].ty);
            params.push(format!("{}{} %p{}", r.ll(), if r == Repr::I1 { " zeroext" } else { "" }, i));
        }
        // prologue: depth check, parameter stores, captures
        g.line("%d0 = load i32, ptr @l2_depth");
        g.line("%d1 = add i32 %d0, 1");
        g.line("store i32 %d1, ptr @l2_depth");
        g.line(&format!("%dov = icmp sgt i32 %d1, {}", crate::interp::MAX_DEPTH));
        g.line("br i1 %dov, label %so, label %start");
        g.label_raw("so");
        g.line("call void @l2_throw_stack_overflow()");
        g.line("br label %exc_exit");
        g.label_raw("start");
        for (i, pid) in f.params.iter().enumerate() {
            let ty = f.locals[*pid as usize].ty.clone();
            let r = repr(&ty);
            let v = V::new(r, format!("%p{}", i), true);
            if f.locals[*pid as usize].cell {
                let b = g.to_box(v, &ty);
                let c = g.call_val(Repr::Ptr, "l2_cell_new", &[b.typed()]);
                g.line(&format!("store ptr {}, ptr %l{}", c, pid));
            } else {
                g.line(&format!("store {} %p{}, ptr %l{}", r.ll(), i, pid));
            }
        }
        for (ci, cap) in f.captures.iter().enumerate() {
            let b = g.call_val(Repr::Ptr, "l2_closure_cap", &["ptr %env".into(), format!("i32 {}", ci)]);
            let info = &f.locals[cap.inner as usize];
            if info.cell {
                let v = if cap.by_ref { b } else { g.call_val(Repr::Ptr, "l2_cell_new", &[format!("ptr {}", b)]) };
                g.line(&format!("store ptr {}, ptr %l{}", v, cap.inner));
            } else {
                let ty = info.ty.clone();
                let v = g.from_box(V::new(Repr::Ptr, b, true), &ty);
                g.line(&format!("store {}, ptr %l{}", v.typed(), cap.inner));
            }
        }
        g.stmts(&f.body);
        if !g.terminated {
            if g.ret_repr != Repr::Void {
                let z = g.ret_repr.zero();
                g.line(&format!("store {} {}, ptr %retval", g.ret_repr.ll(), z));
            }
            g.line("br label %exit");
        }
        // exits
        for (exit, normal) in [("exit", true), ("exc_exit", false)] {
            g.label_raw(exit);
            for (i, r) in g.reprs.clone().iter().enumerate() {
                if *r == Repr::Ptr {
                    let t = g.t();
                    g.line(&format!("{} = load ptr, ptr %l{}", t, i));
                    g.line(&format!("call void @l2_free(ptr {})", t));
                }
            }
            let t = g.t();
            g.line(&format!("{} = load i32, ptr @l2_depth", t));
            let t2 = g.t();
            g.line(&format!("{} = sub i32 {}, 1", t2, t));
            g.line(&format!("store i32 {}, ptr @l2_depth", t2));
            if g.ret_repr == Repr::Void {
                g.line("ret void");
            } else if normal {
                let t = g.t();
                g.line(&format!("{} = load {}, ptr %retval", t, g.ret_repr.ll()));
                g.line(&format!("ret {} {}", g.ret_repr.ll(), t));
            } else {
                g.line(&format!("ret {} {}", g.ret_repr.ll(), g.ret_repr.zero()));
            }
        }
        let mut s = String::new();
        let _ = writeln!(s, "; {}", f.name.replace('\n', " "));
        let _ = writeln!(s, "define internal {}{} @f.{}({}) {{", attr(g.ret_repr), g.ret_repr.ll(), fid, params.join(", "));
        let _ = writeln!(s, "entry:");
        for a in &g.allocas {
            let _ = writeln!(s, "{}", a);
        }
        let _ = writeln!(s, "  br label %body\nbody:");
        for l in &g.body {
            let _ = writeln!(s, "{}", l);
        }
        let _ = writeln!(s, "}}\n");
        s
    }

    // ------------------------------------------------------------------ emission helpers
    fn t(&mut self) -> String {
        self.tmp += 1;
        format!("%t{}", self.tmp)
    }
    fn new_label(&mut self, hint: &str) -> String {
        self.lbl += 1;
        format!("{}.{}", hint, self.lbl)
    }
    fn line(&mut self, s: &str) {
        if self.terminated {
            let l = self.new_label("dead");
            self.label_raw(&l);
        }
        self.body.push(format!("  {}", s));
        let t = s.trim_start();
        if t.starts_with("br ") || t.starts_with("ret") || t.starts_with("switch ") || t.starts_with("unreachable") {
            self.terminated = true;
        }
    }
    fn label_raw(&mut self, l: &str) {
        if !self.terminated && !self.body.is_empty() {
            self.body.push(format!("  br label %{}", l));
        }
        self.body.push(format!("{}:", l));
        self.terminated = false;
        self.cur_label = l.to_string();
    }
    fn br(&mut self, l: &str) {
        self.line(&format!("br label %{}", l));
    }
    fn call(&mut self, ret: Repr, f: &str, args: &[String]) -> Option<String> {
        if ret == Repr::Void {
            self.line(&format!("call void @{}({})", f, args.join(", ")));
            None
        } else {
            let t = self.t();
            self.line(&format!("{} = call {}{} @{}({})", t, attr(ret), ret.ll(), f, args.join(", ")));
            Some(t)
        }
    }
    fn call_val(&mut self, ret: Repr, f: &str, args: &[String]) -> String {
        self.call(ret, f, args).unwrap_or_default()
    }
    fn landing(&self) -> String {
        self.landings.last().cloned().unwrap_or_else(|| "exc_exit".into())
    }
    /// Branches to the current landing block if an exception is pending.
    fn check(&mut self) {
        let t = self.t();
        self.line(&format!("{} = load i8, ptr @L2_PENDING", t));
        let c = self.t();
        self.line(&format!("{} = icmp ne i8 {}, 0", c, t));
        let ok = self.new_label("ok");
        let land = self.landing();
        self.line(&format!("br i1 {}, label %{}, label %{}", c, land, ok));
        self.label_raw(&ok);
    }
    fn str_lit(&mut self, s: &str) -> V {
        let g = self.m.cstr(s);
        let v = self.call_val(Repr::Ptr, "l2_str_lit", &[format!("ptr {}", g), format!("i64 {}", s.len())]);
        V::new(Repr::Ptr, v, true)
    }
    fn type_str(&mut self, t: &Type) -> String {
        let s = rt_type(t).encode();
        self.m.cstr(&s)
    }

    // ------------------------------------------------------------------ ownership helpers
    fn own(&mut self, v: V) -> V {
        if v.r == Repr::Ptr && !v.owned && v.v != "null" {
            let d = self.call_val(Repr::Ptr, "l2_dup", &[v.typed()]);
            return V::new(Repr::Ptr, d, true);
        }
        V { owned: v.r == Repr::Ptr, ..v }
    }
    fn release(&mut self, v: &V) {
        if v.r == Repr::Ptr && v.owned && v.v != "null" {
            self.line(&format!("call void @l2_free(ptr {})", v.v));
        }
    }
    /// Converts any value to an owned box.
    fn to_box(&mut self, v: V, ty: &Type) -> V {
        match v.r {
            Repr::Ptr => self.own(v),
            Repr::I1 => {
                let b = self.call_val(Repr::Ptr, "l2_box_bool", &[format!("i1 zeroext {}", v.v)]);
                V::new(Repr::Ptr, b, true)
            }
            Repr::F32 | Repr::F64 => {
                let d = self.fext(&v);
                let k = float_kind(ty).code();
                let b = self.call_val(Repr::Ptr, "l2_box_f64", &[format!("i8 {}", k), format!("double {}", d)]);
                V::new(Repr::Ptr, b, true)
            }
            Repr::Void => V::new(Repr::Ptr, "null", false),
            _ => {
                let it = int_kind(ty);
                let w = self.iext64(&v, it.signed());
                let b = self.call_val(Repr::Ptr, "l2_box_int", &[format!("i8 {}", it.code()), format!("i64 {}", w)]);
                V::new(Repr::Ptr, b, true)
            }
        }
    }
    /// Converts an owned box to the representation of `ty` (unboxing primitives).
    fn from_box(&mut self, b: V, ty: &Type) -> V {
        let r = repr(ty);
        match r {
            Repr::Ptr => b,
            Repr::Void => {
                self.release(&b);
                V::void()
            }
            Repr::I1 => {
                let v = self.call_val(Repr::I1, "l2_unbox_bool", &[b.typed()]);
                self.release(&b);
                self.check();
                V::new(Repr::I1, v, false)
            }
            Repr::F32 | Repr::F64 => {
                let d = self.call_val(Repr::F64, "l2_unbox_f64", &[b.typed()]);
                self.release(&b);
                self.check();
                let v = if r == Repr::F32 {
                    let t = self.t();
                    self.line(&format!("{} = fptrunc double {} to float", t, d));
                    t
                } else {
                    d
                };
                V::new(r, v, false)
            }
            _ => {
                let i = self.call_val(Repr::I64, "l2_unbox_int", &[b.typed()]);
                self.release(&b);
                self.check();
                let v = self.itrunc(&i, r);
                V::new(r, v, false)
            }
        }
    }
    fn fext(&mut self, v: &V) -> String {
        if v.r == Repr::F32 {
            let t = self.t();
            self.line(&format!("{} = fpext float {} to double", t, v.v));
            t
        } else {
            v.v.clone()
        }
    }
    fn iext64(&mut self, v: &V, signed: bool) -> String {
        if v.r == Repr::I64 {
            return v.v.clone();
        }
        let t = self.t();
        self.line(&format!("{} = {} {} {} to i64", t, if signed { "sext" } else { "zext" }, v.r.ll(), v.v));
        t
    }
    fn itrunc(&mut self, v: &str, r: Repr) -> String {
        if r == Repr::I64 {
            return v.to_string();
        }
        let t = self.t();
        self.line(&format!("{} = trunc i64 {} to {}", t, v, r.ll()));
        t
    }

    // ------------------------------------------------------------------ locals
    fn is_cell(&self, id: LocalId) -> bool {
        self.f.locals[id as usize].cell
    }
    fn load_slot(&mut self, id: LocalId) -> V {
        let r = self.reprs[id as usize];
        let t = self.t();
        self.line(&format!("{} = load {}, ptr %l{}", t, r.ll(), id));
        V::new(r, t, false)
    }
    fn read_local(&mut self, id: LocalId) -> V {
        if self.is_cell(id) {
            let c = self.load_slot(id);
            let b = self.call_val(Repr::Ptr, "l2_ref_get", &[c.typed()]);
            let ty = self.f.locals[id as usize].ty.clone();
            let ty = match ty {
                Type::Ref(false, t) => *t,
                t => t,
            };
            return self.from_box(V::new(Repr::Ptr, b, true), &ty);
        }
        self.load_slot(id)
    }
    /// Stores an owned value into a local, freeing the previous box.
    fn store_local(&mut self, id: LocalId, v: V, drop_old: bool) {
        let ty = self.f.locals[id as usize].ty.clone();
        if self.is_cell(id) {
            let c = self.load_slot(id);
            if c.v.is_empty() {
                return;
            }
            let b = self.to_box(v, &ty);
            if drop_old {
                let old = self.call_val(Repr::Ptr, "l2_ref_get", &[c.typed()]);
                self.line(&format!("call void @l2_drop_value(ptr {})", old));
                self.line(&format!("call void @l2_free(ptr {})", old));
                self.check();
            }
            self.line(&format!("call void @l2_ref_set({}, {})", c.typed(), b.typed()));
            return;
        }
        let r = self.reprs[id as usize];
        if r == Repr::Ptr {
            let old = self.load_slot(id);
            if drop_old {
                self.line(&format!("call void @l2_drop_value(ptr {})", old.v));
                self.check();
            }
            let v = self.own(v);
            self.line(&format!("call void @l2_free(ptr {})", old.v));
            self.line(&format!("store ptr {}, ptr %l{}", v.v, id));
        } else if v.r != Repr::Void {
            self.line(&format!("store {}, ptr %l{}", v.typed(), id));
        }
    }
    /// Runs drop hooks for a local at scope exit and clears it.
    fn drop_local(&mut self, id: LocalId, unwinding: bool) {
        let val = if self.is_cell(id) {
            let c = self.load_slot(id);
            let b = self.call_val(Repr::Ptr, "l2_ref_take", &[c.typed()]);
            V::new(Repr::Ptr, b, true)
        } else {
            let v = self.load_slot(id);
            self.line(&format!("store ptr null, ptr %l{}", id));
            V::new(Repr::Ptr, v.v, true)
        };
        self.line(&format!("call void @l2_drop_value(ptr {})", val.v));
        self.line(&format!("call void @l2_free(ptr {})", val.v));
        if unwinding {
            // exceptions raised by drop() while unwinding are discarded
            let e = self.call_val(Repr::Ptr, "l2_take_pending", &[]);
            self.line(&format!("call void @l2_free(ptr {})", e));
        } else {
            self.check();
        }
    }

    // ------------------------------------------------------------------ cleanups
    fn emit_cleanups(&mut self, depth: usize) {
        let n = self.cleanups.len();
        for i in (depth..n).rev() {
            match &self.cleanups[i] {
                Clean::Finally { body, landing_depth } => {
                    let (body, ld) = (*body, *landing_depth);
                    let saved_l: Vec<String> = self.landings.drain(ld..).collect();
                    let saved_c: Vec<Clean<'h>> = self.cleanups.drain(i..).collect();
                    self.stmts(body);
                    self.cleanups.extend(saved_c);
                    self.landings.extend(saved_l);
                }
                Clean::Drops { locals, landing_depth } => {
                    let (ls, ld) = (locals.clone(), *landing_depth);
                    let saved_l: Vec<String> = self.landings.drain(ld..).collect();
                    for l in ls.iter().rev() {
                        self.drop_local(*l, false);
                    }
                    self.landings.extend(saved_l);
                }
            }
        }
    }

    // ------------------------------------------------------------------ statements
    fn stmts(&mut self, ss: &'h [Stmt]) {
        for s in ss {
            self.stmt(s);
        }
    }

    fn stmt(&mut self, s: &'h Stmt) {
        match &s.kind {
            StmtKind::Let(id, init) => {
                let v = match init {
                    Some(e) => {
                        let v = self.expr(e);
                        let ty = self.f.locals[*id as usize].ty.clone();
                        self.adapt(v, &e.ty, &ty)
                    }
                    None => V::new(self.reprs[*id as usize], self.reprs[*id as usize].zero(), false),
                };
                if self.is_cell(*id) {
                    let ty = self.f.locals[*id as usize].ty.clone();
                    let old = self.load_slot(*id);
                    self.line(&format!("call void @l2_free(ptr {})", old.v));
                    let b = if init.is_some() { self.to_box(v, &ty) } else { V::new(Repr::Ptr, "null", false) };
                    let c = self.call_val(Repr::Ptr, "l2_cell_new", &[b.typed()]);
                    self.line(&format!("store ptr {}, ptr %l{}", c, id));
                } else {
                    self.store_local(*id, v, false);
                }
            }
            StmtKind::Assign(place, e) => {
                let drop_old = self.ownership && self.m.p.needs_drop(&e.ty);
                let v = self.expr(e);
                self.assign(place, v, &e.ty, drop_old);
            }
            StmtKind::Expr(e) => {
                let v = self.expr(e);
                if self.ownership && self.m.p.needs_drop(&e.ty) && !matches!(e.kind, ExprKind::Local(_) | ExprKind::Field(..)) && v.r == Repr::Ptr {
                    self.line(&format!("call void @l2_drop_value(ptr {})", v.v));
                    self.release(&v);
                    self.check();
                } else {
                    self.release(&v);
                }
            }
            StmtKind::Free(e) => {
                let v = self.expr(e);
                self.line(&format!("call void @l2_free_manual({})", v.typed()));
                self.release(&v);
                self.check();
            }
            StmtKind::If(c, a, b) => {
                let cv = self.expr(c);
                let (lt, le, lend) = (self.new_label("then"), self.new_label("else"), self.new_label("endif"));
                self.line(&format!("br i1 {}, label %{}, label %{}", cv.v, lt, le));
                self.label_raw(&lt);
                self.stmts(a);
                self.br(&lend);
                self.label_raw(&le);
                self.stmts(b);
                self.br(&lend);
                self.label_raw(&lend);
            }
            StmtKind::Loop { cond, body, step } => {
                let (lc, lb, ls, lx) = (self.new_label("cond"), self.new_label("loop"), self.new_label("step"), self.new_label("endloop"));
                self.br(&lc);
                self.label_raw(&lc);
                match cond {
                    Some(c) => {
                        let cv = self.expr(c);
                        self.line(&format!("br i1 {}, label %{}, label %{}", cv.v, lb, lx));
                    }
                    None => self.br(&lb),
                }
                self.label_raw(&lb);
                self.brks.push(Brk { is_loop: true, break_lbl: lx.clone(), cont_lbl: ls.clone(), depth: self.cleanups.len() });
                self.stmts(body);
                self.brks.pop();
                self.br(&ls);
                self.label_raw(&ls);
                self.stmts(step);
                self.br(&lc);
                self.label_raw(&lx);
            }
            StmtKind::Break => {
                let b = self.brks.last().unwrap();
                let (lbl, depth) = (b.break_lbl.clone(), b.depth);
                self.emit_cleanups(depth);
                self.br(&lbl);
            }
            StmtKind::Continue => {
                let b = self.brks.iter().rev().find(|b| b.is_loop).unwrap();
                let (lbl, depth) = (b.cont_lbl.clone(), b.depth);
                self.emit_cleanups(depth);
                self.br(&lbl);
            }
            StmtKind::Return(e) => {
                if let Some(e) = e {
                    let v = self.expr(e);
                    let v = self.adapt(v, &e.ty, &self.f.ret.clone());
                    let v = self.own(v);
                    if self.ret_repr != Repr::Void && v.r != Repr::Void {
                        self.line(&format!("store {}, ptr %retval", v.typed()));
                    }
                }
                self.emit_cleanups(0);
                self.br("exit");
            }
            StmtKind::Throw(e) => {
                let v = self.expr(e);
                let v = self.own(v);
                self.line(&format!("call void @l2_throw({})", v.typed()));
                let l = self.landing();
                self.br(&l);
            }
            StmtKind::Block { body, drops } => {
                if drops.is_empty() {
                    self.stmts(body);
                    return;
                }
                let land = self.new_label("drop");
                let after = self.new_label("after");
                self.cleanups.push(Clean::Drops { locals: drops.clone(), landing_depth: self.landings.len() });
                self.landings.push(land.clone());
                self.stmts(body);
                self.landings.pop();
                self.cleanups.pop();
                for l in drops.iter().rev() {
                    self.drop_local(*l, false);
                }
                self.br(&after);
                self.label_raw(&land);
                let e = self.call_val(Repr::Ptr, "l2_take_pending", &[]);
                for l in drops.iter().rev() {
                    self.drop_local(*l, true);
                }
                self.line(&format!("call void @l2_set_pending(ptr {})", e));
                let outer = self.landing();
                self.br(&outer);
                self.label_raw(&after);
            }
            StmtKind::Try { body, catches, finally } => self.try_stmt(body, catches, finally.as_deref()),
            StmtKind::Switch { cases } => {
                let end = self.new_label("endsw");
                let bodies: Vec<String> = cases.iter().map(|_| self.new_label("case")).collect();
                for (i, c) in cases.iter().enumerate() {
                    if let Some(cond) = &c.cond {
                        let cv = self.expr(cond);
                        let next = self.new_label("next");
                        self.line(&format!("br i1 {}, label %{}, label %{}", cv.v, bodies[i], next));
                        self.label_raw(&next);
                    }
                }
                match cases.iter().position(|c| c.cond.is_none()) {
                    Some(d) => self.br(&bodies[d].clone()),
                    None => self.br(&end),
                }
                self.brks.push(Brk { is_loop: false, break_lbl: end.clone(), cont_lbl: String::new(), depth: self.cleanups.len() });
                for (i, c) in cases.iter().enumerate() {
                    self.label_raw(&bodies[i]);
                    self.stmts(&c.body);
                    if c.fallthrough && i + 1 < cases.len() {
                        self.br(&bodies[i + 1].clone());
                    } else {
                        self.br(&end);
                    }
                }
                self.brks.pop();
                self.label_raw(&end);
            }
        }
    }

    fn try_stmt(&mut self, body: &'h [Stmt], catches: &'h [Catch], finally: Option<&'h [Stmt]>) {
        let end = self.new_label("endtry");
        let fin_lbl = finally.map(|_| self.new_label("finally"));
        if let (Some(fb), Some(fl)) = (finally, &fin_lbl) {
            self.cleanups.push(Clean::Finally { body: fb, landing_depth: self.landings.len() });
            self.landings.push(fl.clone());
        }
        let catch_lbl = if catches.is_empty() { None } else { Some(self.new_label("catch")) };
        if let Some(cl) = &catch_lbl {
            self.landings.push(cl.clone());
        }
        self.stmts(body);
        if catch_lbl.is_some() {
            self.landings.pop();
        }
        if finally.is_some() {
            let d = self.cleanups.len() - 1;
            self.emit_cleanups(d);
        }
        self.br(&end);
        if let Some(cl) = catch_lbl {
            self.label_raw(&cl);
            let e = self.call_val(Repr::Ptr, "l2_take_pending", &[]);
            for c in catches {
                let list = self.m.list(&c.classes);
                let m = self.call_val(Repr::I1, "l2_exc_matches", &[format!("ptr {}", e), format!("ptr {}", list), format!("i32 {}", c.classes.len())]);
                let (lc, ln) = (self.new_label("catchbody"), self.new_label("nextcatch"));
                self.line(&format!("br i1 {}, label %{}, label %{}", m, lc, ln));
                self.label_raw(&lc);
                self.store_local(c.local, V::new(Repr::Ptr, e.clone(), true), false);
                self.stmts(&c.body);
                if finally.is_some() {
                    let d = self.cleanups.len() - 1;
                    self.emit_cleanups(d);
                }
                self.br(&end);
                self.label_raw(&ln);
            }
            self.line(&format!("call void @l2_set_pending(ptr {})", e));
            let l = self.landing();
            self.br(&l);
        }
        if let (Some(fb), Some(fl)) = (finally, fin_lbl) {
            self.cleanups.pop();
            self.landings.pop();
            self.label_raw(&fl);
            let e = self.call_val(Repr::Ptr, "l2_take_pending", &[]);
            self.stmts(fb);
            self.line(&format!("call void @l2_set_pending(ptr {})", e));
            let l = self.landing();
            self.br(&l);
        }
        self.label_raw(&end);
    }

    /// Adapts a value of one static type to the representation of another (identical types in
    /// well-typed HIR, but `&T` vs `T` and `*T` locals may need adjustment).
    fn adapt(&mut self, v: V, _from: &Type, to: &Type) -> V {
        let r = repr(to);
        if v.r == r || v.r == Repr::Void || r == Repr::Void {
            return v;
        }
        if r == Repr::Ptr {
            return self.to_box(v, _from);
        }
        if v.r == Repr::Ptr {
            let v = self.own(v);
            return self.from_box(v, to);
        }
        v
    }

    fn assign(&mut self, place: &'h Place, v: V, ty: &Type, drop_old: bool) {
        match place {
            Place::Local(id) => {
                let lt = self.f.locals[*id as usize].ty.clone();
                let v = self.adapt(v, ty, &lt);
                self.store_local(*id, v, drop_old);
            }
            Place::Deref(id) => {
                let r = self.load_slot(*id);
                let b = self.to_box(v, ty);
                if drop_old {
                    let old = self.call_val(Repr::Ptr, "l2_ref_get", &[r.typed()]);
                    self.line(&format!("call void @l2_drop_value(ptr {})", old));
                    self.line(&format!("call void @l2_free(ptr {})", old));
                    self.check();
                }
                self.line(&format!("call void @l2_ref_set({}, {})", r.typed(), b.typed()));
            }
            Place::Field(o, idx) => {
                let ov = self.expr(o);
                if drop_old {
                    let old = self.call_val(Repr::Ptr, "l2_get_field", &[ov.typed(), format!("i32 {}", idx)]);
                    self.line(&format!("call void @l2_drop_value(ptr {})", old));
                    self.line(&format!("call void @l2_free(ptr {})", old));
                    self.check();
                }
                self.set_field(&ov, *idx, v, ty);
                self.release(&ov);
                self.check();
            }
            Place::Global(g) => {
                let c = self.t();
                self.line(&format!("{} = load ptr, ptr @g.{}", c, g));
                let b = self.to_box(v, ty);
                if drop_old {
                    let old = self.call_val(Repr::Ptr, "l2_ref_get", &[format!("ptr {}", c)]);
                    self.line(&format!("call void @l2_drop_value(ptr {})", old));
                    self.line(&format!("call void @l2_free(ptr {})", old));
                    self.check();
                }
                self.line(&format!("call void @l2_ref_set(ptr {}, {})", c, b.typed()));
            }
        }
    }

    fn set_field(&mut self, ov: &V, idx: u32, v: V, ty: &Type) {
        match v.r {
            Repr::I1 => self.line(&format!("call void @l2_set_field_bool({}, i32 {}, i1 zeroext {})", ov.typed(), idx, v.v)),
            Repr::F32 | Repr::F64 => {
                let d = self.fext(&v);
                self.line(&format!("call void @l2_set_field_f64({}, i32 {}, i8 {}, double {})", ov.typed(), idx, float_kind(ty).code(), d));
            }
            Repr::Ptr => {
                let v = self.own(v);
                self.line(&format!("call void @l2_set_field({}, i32 {}, {})", ov.typed(), idx, v.typed()));
            }
            Repr::Void => {}
            _ => {
                let it = int_kind(ty);
                let w = self.iext64(&v, it.signed());
                self.line(&format!("call void @l2_set_field_int({}, i32 {}, i8 {}, i64 {})", ov.typed(), idx, it.code(), w));
            }
        }
    }

    /// Pushes owned boxes for `xs` into a stack array; returns (array, boxes).
    fn box_array(&mut self, xs: &'h [Expr]) -> (String, Vec<V>) {
        let mut boxes = Vec::new();
        for x in xs {
            let v = self.expr(x);
            let b = self.to_box(v, &x.ty);
            boxes.push(b);
        }
        let arr = self.array_of(&boxes);
        (arr, boxes)
    }

    fn array_of(&mut self, boxes: &[V]) -> String {
        if boxes.is_empty() {
            return "null".into();
        }
        let a = self.t();
        self.allocas.push(format!("  {} = alloca [{} x ptr]", a, boxes.len()));
        for (i, b) in boxes.iter().enumerate() {
            let p = self.t();
            self.line(&format!("{} = getelementptr [{} x ptr], ptr {}, i32 0, i32 {}", p, boxes.len(), a, i));
            self.line(&format!("store {}, ptr {}", b.typed(), p));
        }
        a
    }

    fn place_ref(&mut self, p: &'h Place) -> V {
        match p {
            Place::Local(id) => {
                let c = self.load_slot(*id);
                if self.is_cell(*id) {
                    self.own(c)
                } else {
                    // a non-cell local referenced: wrap the current value into a fresh cell
                    let ty = self.f.locals[*id as usize].ty.clone();
                    let b = self.to_box(c, &ty);
                    let cell = self.call_val(Repr::Ptr, "l2_cell_new", &[b.typed()]);
                    V::new(Repr::Ptr, cell, true)
                }
            }
            Place::Deref(id) => {
                let c = self.load_slot(*id);
                self.own(c)
            }
            Place::Field(o, idx) => {
                let ov = self.expr(o);
                let r = self.call_val(Repr::Ptr, "l2_field_ref", &[ov.typed(), format!("i32 {}", idx)]);
                self.release(&ov);
                self.check();
                V::new(Repr::Ptr, r, true)
            }
            Place::Global(g) => {
                let c = self.t();
                self.line(&format!("{} = load ptr, ptr @g.{}", c, g));
                self.own(V::new(Repr::Ptr, c, false))
            }
        }
    }

    // ------------------------------------------------------------------ expressions
    fn expr(&mut self, e: &'h Expr) -> V {
        let r = repr(&e.ty);
        match &e.kind {
            ExprKind::Lit(l) => match l {
                Lit::Int(v) => match r {
                    Repr::F32 | Repr::F64 => V::new(r, float_lit(*v as f64, r), false),
                    Repr::Ptr => {
                        let s = v.to_string();
                        let g = self.m.cstr(&s);
                        let b = self.call_val(Repr::Ptr, "l2_big_lit", &[format!("ptr {}", g), format!("i64 {}", s.len())]);
                        V::new(Repr::Ptr, b, true)
                    }
                    _ => {
                        let bits = int_kind(&e.ty).bits();
                        let m = if bits == 64 { *v as u64 as i64 as i128 } else { IntTy::from_code(match bits { 8 => 0, 16 => 1, 32 => 2, _ => 3 }).wrap(*v) };
                        V::new(r, m.to_string(), false)
                    }
                },
                Lit::Float(v) => match r {
                    Repr::F32 | Repr::F64 => V::new(r, float_lit(*v, r), false),
                    _ => {
                        let b = self.call_val(Repr::Ptr, "l2_box_f64", &["i8 2".into(), format!("double {}", float_lit(*v, Repr::F64))]);
                        V::new(Repr::Ptr, b, true)
                    }
                },
                Lit::Bool(b) => V::new(Repr::I1, if *b { "true" } else { "false" }, false),
                Lit::Str(s) => self.str_lit(s),
                Lit::Big(s) => {
                    let g = self.m.cstr(s);
                    let b = self.call_val(Repr::Ptr, "l2_big_lit", &[format!("ptr {}", g), format!("i64 {}", s.len())]);
                    V::new(Repr::Ptr, b, true)
                }
                Lit::Null => V::new(Repr::Ptr, "null", false),
                Lit::Void => V::void(),
            },
            ExprKind::Local(id) => {
                let lt = &self.f.locals[*id as usize].ty;
                if matches!(lt, Type::Ref(true, _)) && matches!(e.ty, Type::Ref(true, _)) {
                    return self.load_slot(*id);
                }
                self.read_local(*id)
            }
            ExprKind::Move(id) => {
                if !self.ownership {
                    return self.read_local(*id);
                }
                if self.is_cell(*id) {
                    let c = self.load_slot(*id);
                    let b = self.call_val(Repr::Ptr, "l2_ref_take", &[c.typed()]);
                    let ty = e.ty.clone();
                    return self.from_box(V::new(Repr::Ptr, b, true), &ty);
                }
                let v = self.load_slot(*id);
                if v.r == Repr::Ptr {
                    self.line(&format!("store ptr null, ptr %l{}", id));
                    return V::new(Repr::Ptr, v.v, true);
                }
                v
            }
            ExprKind::Deref(inner) => {
                let rv = match inner.kind {
                    ExprKind::Local(id) => self.load_slot(id),
                    _ => self.expr(inner),
                };
                let b = self.call_val(Repr::Ptr, "l2_ref_get", &[rv.typed()]);
                self.release(&rv);
                let ty = e.ty.clone();
                self.from_box(V::new(Repr::Ptr, b, true), &ty)
            }
            ExprKind::Global(g) => {
                let c = self.t();
                self.line(&format!("{} = load ptr, ptr @g.{}", c, g));
                let b = self.call_val(Repr::Ptr, "l2_ref_get", &[format!("ptr {}", c)]);
                let ty = e.ty.clone();
                self.from_box(V::new(Repr::Ptr, b, true), &ty)
            }
            ExprKind::Field(o, idx) => {
                let ov = self.expr(o);
                let res = match r {
                    Repr::I1 => V::new(r, self.call_val(Repr::I1, "l2_get_field_bool", &[ov.typed(), format!("i32 {}", idx)]), false),
                    Repr::F32 | Repr::F64 => {
                        let d = self.call_val(Repr::F64, "l2_get_field_f64", &[ov.typed(), format!("i32 {}", idx)]);
                        if r == Repr::F32 {
                            let t = self.t();
                            self.line(&format!("{} = fptrunc double {} to float", t, d));
                            V::new(r, t, false)
                        } else {
                            V::new(r, d, false)
                        }
                    }
                    Repr::Ptr | Repr::Void => V::new(Repr::Ptr, self.call_val(Repr::Ptr, "l2_get_field", &[ov.typed(), format!("i32 {}", idx)]), true),
                    _ => {
                        let i = self.call_val(Repr::I64, "l2_get_field_int", &[ov.typed(), format!("i32 {}", idx)]);
                        let t = self.itrunc(&i, r);
                        V::new(r, t, false)
                    }
                };
                self.release(&ov);
                self.check();
                res
            }
            ExprKind::TupleGet(t, i) => {
                let tv = self.expr(t);
                let b = self.call_val(Repr::Ptr, "l2_tuple_get", &[tv.typed(), format!("i32 {}", i)]);
                self.release(&tv);
                self.check();
                let ty = e.ty.clone();
                self.from_box(V::new(Repr::Ptr, b, true), &ty)
            }
            ExprKind::Unary(op, a) => {
                let av = self.expr(a);
                match (op, av.r) {
                    (UnaryOp::Not, _) => {
                        let t = self.t();
                        self.line(&format!("{} = xor i1 {}, true", t, av.v));
                        V::new(Repr::I1, t, false)
                    }
                    (UnaryOp::Neg, Repr::F32 | Repr::F64) => {
                        let t = self.t();
                        self.line(&format!("{} = fneg {}", t, av.typed()));
                        V::new(av.r, t, false)
                    }
                    (UnaryOp::Neg, Repr::Ptr) => {
                        let b = self.call_val(Repr::Ptr, "l2_negate", &[av.typed(), format!("i1 zeroext {}", self.f.wrap)]);
                        self.release(&av);
                        self.check();
                        V::new(Repr::Ptr, b, true)
                    }
                    (UnaryOp::Neg, _) => {
                        let it = int_kind(&e.ty);
                        self.int_arith_op(ArithOp::Sub, it, V::new(av.r, "0", false), av, self.f.wrap, true)
                    }
                    (UnaryOp::BitNot, Repr::Ptr) => {
                        let b = self.call_val(Repr::Ptr, "l2_bitnot", &[av.typed()]);
                        self.release(&av);
                        V::new(Repr::Ptr, b, true)
                    }
                    (UnaryOp::BitNot, _) => {
                        let t = self.t();
                        self.line(&format!("{} = xor {}, -1", t, av.typed()));
                        V::new(av.r, t, false)
                    }
                }
            }
            ExprKind::Arith(op, a, b, wrap) => {
                let av = self.expr(a);
                let bv = self.expr(b);
                self.arith(*op, &e.ty, av, &a.ty, bv, &b.ty, *wrap)
            }
            ExprKind::Concat(parts) => {
                let sb = self.call_val(Repr::Ptr, "l2_sb_new", &[]);
                for p in parts {
                    if let ExprKind::Lit(Lit::Str(s)) = &p.kind {
                        if !s.is_empty() {
                            let g = self.m.cstr(s);
                            self.line(&format!("call void @l2_sb_push_lit(ptr {}, ptr {}, i64 {})", sb, g, s.len()));
                        }
                        continue;
                    }
                    let v = self.expr(p);
                    match v.r {
                        Repr::I1 => self.line(&format!("call void @l2_sb_push_bool(ptr {}, i1 zeroext {})", sb, v.v)),
                        Repr::F32 | Repr::F64 => {
                            let d = self.fext(&v);
                            self.line(&format!("call void @l2_sb_push_f64(ptr {}, i8 {}, double {})", sb, float_kind(&p.ty).code(), d));
                        }
                        Repr::Ptr => {
                            self.line(&format!("call void @l2_sb_push_box(ptr {}, ptr {})", sb, v.v));
                            self.release(&v);
                            self.check();
                        }
                        Repr::Void => {}
                        _ => {
                            let it = int_kind(&p.ty);
                            let w = self.iext64(&v, it.signed());
                            self.line(&format!("call void @l2_sb_push_int(ptr {}, i8 {}, i64 {})", sb, it.code(), w));
                        }
                    }
                }
                let s = self.call_val(Repr::Ptr, "l2_sb_finish", &[format!("ptr {}", sb)]);
                V::new(Repr::Ptr, s, true)
            }
            ExprKind::Cmp(op, a, b) => {
                let av = self.expr(a);
                let bv = self.expr(b);
                self.compare(*op, av, &a.ty, bv, &b.ty)
            }
            ExprKind::And(a, b) | ExprKind::Or(a, b) => {
                let is_and = matches!(e.kind, ExprKind::And(..));
                let av = self.expr(a);
                let from = self.cur_label.clone();
                let (lr, lend) = (self.new_label("rhs"), self.new_label("sc"));
                if is_and {
                    self.line(&format!("br i1 {}, label %{}, label %{}", av.v, lr, lend));
                } else {
                    self.line(&format!("br i1 {}, label %{}, label %{}", av.v, lend, lr));
                }
                self.label_raw(&lr);
                let bv = self.expr(b);
                let from_b = self.cur_label.clone();
                self.br(&lend);
                self.label_raw(&lend);
                let t = self.t();
                self.line(&format!("{} = phi i1 [ {}, %{} ], [ {}, %{} ]", t, if is_and { "false" } else { "true" }, from, bv.v, from_b));
                V::new(Repr::I1, t, false)
            }
            ExprKind::Ternary(c, a, b) => {
                let cv = self.expr(c);
                let (la, lb, lend) = (self.new_label("ta"), self.new_label("tb"), self.new_label("tend"));
                self.line(&format!("br i1 {}, label %{}, label %{}", cv.v, la, lb));
                self.label_raw(&la);
                let av = self.expr(a);
                let av = self.own(av);
                let fa = self.cur_label.clone();
                self.br(&lend);
                self.label_raw(&lb);
                let bv = self.expr(b);
                let bv = self.own(bv);
                let fb = self.cur_label.clone();
                self.br(&lend);
                self.label_raw(&lend);
                if r == Repr::Void {
                    return V::void();
                }
                let t = self.t();
                self.line(&format!("{} = phi {} [ {}, %{} ], [ {}, %{} ]", t, r.ll(), av.v, fa, bv.v, fb));
                V::new(r, t, r == Repr::Ptr)
            }
            ExprKind::Coalesce(a, b) => {
                let av = self.expr(a);
                let av = self.own(av);
                let isnull = self.t();
                self.line(&format!("{} = icmp eq ptr {}, null", isnull, av.v));
                let (lnn, lnull, lend) = (self.new_label("nn"), self.new_label("isnull"), self.new_label("coal"));
                self.line(&format!("br i1 {}, label %{}, label %{}", isnull, lnull, lnn));
                self.label_raw(&lnn);
                let ty = e.ty.clone();
                let x = self.from_box(av, &ty);
                let fx = self.cur_label.clone();
                self.br(&lend);
                self.label_raw(&lnull);
                let bv = self.expr(b);
                let bv = self.adapt(bv, &b.ty, &ty);
                let bv = self.own(bv);
                let fy = self.cur_label.clone();
                self.br(&lend);
                self.label_raw(&lend);
                let t = self.t();
                self.line(&format!("{} = phi {} [ {}, %{} ], [ {}, %{} ]", t, r.ll(), x.v, fx, bv.v, fy));
                V::new(r, t, r == Repr::Ptr)
            }
            ExprKind::NonNull(a) => {
                let av = self.expr(a);
                let tuple = matches!(a.ty, Type::Tuple(_));
                self.line(&format!("call void @l2_nonnull({}, i1 zeroext {})", av.typed(), tuple));
                self.check();
                if r == Repr::Ptr {
                    av
                } else {
                    let av = self.own(av);
                    let ty = e.ty.clone();
                    self.from_box(av, &ty)
                }
            }
            ExprKind::Unwrap(a) => {
                let av = self.expr(a);
                if r == Repr::Ptr || av.r != Repr::Ptr {
                    av
                } else {
                    let av = self.own(av);
                    let ty = e.ty.clone();
                    self.from_box(av, &ty)
                }
            }
            ExprKind::Convert(a) => {
                let av = self.expr(a);
                self.convert(av, &a.ty, &e.ty)
            }
            ExprKind::Cast(a, wrap) => {
                let av = self.expr(a);
                let b = self.to_box(av, &a.ty);
                let ts = self.type_str(&e.ty);
                let rb = self.call_val(Repr::Ptr, "l2_cast", &[b.typed(), format!("ptr {}", ts), format!("i1 zeroext {}", wrap)]);
                self.release(&b);
                self.check();
                let ty = e.ty.clone();
                self.from_box(V::new(Repr::Ptr, rb, true), &ty)
            }
            ExprKind::Call(f, args) => {
                let (ps, ret) = self.m.sig(*f);
                let mut a = Vec::new();
                for (x, pr) in args.iter().zip(ps.iter()) {
                    let v = self.expr(x);
                    let v = if *pr == Repr::Ptr { self.to_box(v, &x.ty) } else { v };
                    a.push(format!("{}{} {}", pr.ll(), if *pr == Repr::I1 { " zeroext" } else { "" }, v.v));
                }
                let v = self.call(ret, &format!("f.{}", f), &a);
                self.check();
                V::new(ret, v.unwrap_or_default(), ret == Repr::Ptr)
            }
            ExprKind::CallVirtual(sel, args) => {
                let s = &self.m.p.selectors[*sel as usize];
                let mut ps = vec![Repr::Ptr];
                ps.extend(s.params.iter().map(repr));
                let ret = repr(&s.ret);
                let mut a = Vec::new();
                for (x, pr) in args.iter().zip(ps.iter()) {
                    let v = self.expr(x);
                    let v = if *pr == Repr::Ptr { self.to_box(v, &x.ty) } else { v };
                    a.push(format!("{}{} {}", pr.ll(), if *pr == Repr::I1 { " zeroext" } else { "" }, v.v));
                }
                let v = self.call(ret, &format!("sel.{}", sel), &a);
                self.check();
                V::new(ret, v.unwrap_or_default(), ret == Repr::Ptr)
            }
            ExprKind::CallClosure(c, args) => {
                let (pts, rt) = match c.ty.deref() {
                    Type::Func(p, r) => (p.clone(), (**r).clone()),
                    _ => (vec![], Type::Void),
                };
                let cv = self.expr(c);
                let fp = self.call_val(Repr::Ptr, "l2_closure_fn", &[cv.typed()]);
                self.check();
                let mut a = vec![format!("ptr {}", cv.v)];
                for (x, pt) in args.iter().zip(pts.iter()) {
                    let v = self.expr(x);
                    let pr = repr(pt);
                    let v = if pr == Repr::Ptr { self.to_box(v, &x.ty) } else { v };
                    a.push(format!("{}{} {}", pr.ll(), if pr == Repr::I1 { " zeroext" } else { "" }, v.v));
                }
                let ret = repr(&rt);
                let res = if ret == Repr::Void {
                    self.line(&format!("call void {}({})", fp, a.join(", ")));
                    V::void()
                } else {
                    let t = self.t();
                    self.line(&format!("{} = call {}{} {}({})", t, attr(ret), ret.ll(), fp, a.join(", ")));
                    V::new(ret, t, ret == Repr::Ptr)
                };
                self.release(&cv);
                self.check();
                res
            }
            ExprKind::New(c, ctor, args) => {
                let obj = self.call_val(Repr::Ptr, "l2_new_object", &[format!("i32 {}", c)]);
                let this = self.call_val(Repr::Ptr, "l2_dup", &[format!("ptr {}", obj)]);
                let (ps, _) = self.m.sig(*ctor);
                let mut a = vec![format!("ptr {}", this)];
                for (x, pr) in args.iter().zip(ps.iter().skip(1)) {
                    let v = self.expr(x);
                    let v = if *pr == Repr::Ptr { self.to_box(v, &x.ty) } else { v };
                    a.push(format!("{}{} {}", pr.ll(), if *pr == Repr::I1 { " zeroext" } else { "" }, v.v));
                }
                self.line(&format!("call void @f.{}({})", ctor, a.join(", ")));
                // the object is still owned here; on exception it leaks rather than double-frees
                self.check();
                V::new(Repr::Ptr, obj, true)
            }
            ExprKind::Builtin(b, args) => {
                let (arr, boxes) = self.box_array(args);
                let res = self.call_val(Repr::Ptr, "l2_builtin", &[format!("i16 {}", *b as u16), format!("ptr {}", arr), format!("i32 {}", boxes.len())]);
                for bx in &boxes {
                    self.release(bx);
                }
                self.check();
                let ty = e.ty.clone();
                self.from_box(V::new(Repr::Ptr, res, true), &ty)
            }
            ExprKind::BuiltinMut(b, place, args) => {
                let (arr, boxes) = self.box_array(args);
                let id = *b as u16;
                let n = boxes.len();
                let res = match &**place {
                    Place::Local(l) if !self.is_cell(*l) => {
                        if self.reprs[*l as usize] == Repr::Ptr {
                            self.call_val(Repr::Ptr, "l2_builtin_mut_slot", &[format!("i16 {}", id), format!("ptr %l{}", l), format!("ptr {}", arr), format!("i32 {}", n)])
                        } else {
                            // primitive local: box into a temporary slot, mutate, unbox back
                            let lty = self.f.locals[*l as usize].ty.clone();
                            let cur = self.load_slot(*l);
                            let bx = self.to_box(cur, &lty);
                            let slot = self.t();
                            self.allocas.push(format!("  {} = alloca ptr", slot));
                            self.line(&format!("store ptr {}, ptr {}", bx.v, slot));
                            let r = self.call_val(Repr::Ptr, "l2_builtin_mut_slot", &[format!("i16 {}", id), format!("ptr {}", slot), format!("ptr {}", arr), format!("i32 {}", n)]);
                            let nb = self.t();
                            self.line(&format!("{} = load ptr, ptr {}", nb, slot));
                            let nv = self.from_box(V::new(Repr::Ptr, nb, true), &lty);
                            self.line(&format!("store {}, ptr %l{}", nv.typed(), l));
                            r
                        }
                    }
                    p => {
                        let rv = self.place_ref(p);
                        let r = self.call_val(Repr::Ptr, "l2_builtin_mut_ref", &[format!("i16 {}", id), rv.typed(), format!("ptr {}", arr), format!("i32 {}", n)]);
                        self.release(&rv);
                        r
                    }
                };
                for bx in &boxes {
                    self.release(bx);
                }
                self.check();
                let ty = e.ty.clone();
                self.from_box(V::new(Repr::Ptr, res, true), &ty)
            }
            ExprKind::Lambda(f, caps) => {
                let mut boxes = Vec::new();
                for c in caps {
                    let b = match c {
                        CaptureSrc::Ref(p) => self.place_ref(p),
                        CaptureSrc::Value(x) => {
                            let v = self.expr(x);
                            self.to_box(v, &x.ty)
                        }
                    };
                    boxes.push(b);
                }
                let arr = self.array_of(&boxes);
                let c = self.call_val(Repr::Ptr, "l2_closure_new", &[format!("ptr @f.{}", f), format!("ptr {}", arr), format!("i32 {}", boxes.len())]);
                for b in &boxes {
                    self.release(b);
                }
                V::new(Repr::Ptr, c, true)
            }
            ExprKind::FuncRef(f) => {
                self.m.closure_wrappers.insert(*f);
                let c = self.call_val(Repr::Ptr, "l2_closure_new", &[format!("ptr @f.{}.clo", f), "ptr null".into(), "i32 0".into()]);
                V::new(Repr::Ptr, c, true)
            }
            ExprKind::Dict(kv) => {
                let mut boxes = Vec::new();
                for (k, v) in kv {
                    let kv_ = self.expr(k);
                    let kb = self.to_box(kv_, &k.ty);
                    boxes.push(kb);
                    let vv = self.expr(v);
                    let vb = self.to_box(vv, &v.ty);
                    boxes.push(vb);
                }
                let arr = self.array_of(&boxes);
                let d = self.call_val(Repr::Ptr, "l2_make_dict", &[format!("ptr {}", arr), format!("i32 {}", kv.len())]);
                for b in &boxes {
                    self.release(b);
                }
                V::new(Repr::Ptr, d, true)
            }
            ExprKind::Tuple(xs) => {
                let (arr, boxes) = self.box_array(xs);
                let t = self.call_val(Repr::Ptr, "l2_make_tuple", &[format!("ptr {}", arr), format!("i32 {}", boxes.len())]);
                for b in &boxes {
                    self.release(b);
                }
                V::new(Repr::Ptr, t, true)
            }
            ExprKind::RefMut(p) => self.place_ref(p),
            ExprKind::Seq(stmts, x) => {
                self.stmts(stmts);
                self.expr(x)
            }
        }
    }

    fn convert(&mut self, v: V, from: &Type, to: &Type) -> V {
        let (fr, tr) = (v.r, repr(to));
        let from = from.deref();
        match (fr, tr) {
            (_, Repr::Ptr) if fr != Repr::Ptr => {
                let b = self.to_box(v, from);
                self.widen_box(b, from, to)
            }
            (Repr::Ptr, Repr::Ptr) => self.widen_box(v, from, to),
            (Repr::Ptr, _) => {
                let v = self.own(v);
                self.from_box(v, to)
            }
            (a, b) if a.is_int() && b.is_int() => {
                if a == b {
                    return v;
                }
                let signed = int_kind(from).signed();
                let t = self.t();
                let (wa, wb) = (int_width(a), int_width(b));
                let op = if wb > wa {
                    if signed {
                        "sext"
                    } else {
                        "zext"
                    }
                } else {
                    "trunc"
                };
                self.line(&format!("{} = {} {} to {}", t, op, v.typed(), b.ll()));
                V::new(b, t, false)
            }
            (a, Repr::F32 | Repr::F64) if a.is_int() => {
                let signed = int_kind(from).signed();
                let t = self.t();
                self.line(&format!("{} = {} {} to {}", t, if signed { "sitofp" } else { "uitofp" }, v.typed(), tr.ll()));
                if float_kind(to) == FloatTy::F16 {
                    let r = self.call_val(Repr::F32, "l2_round_f16", &[format!("float {}", t)]);
                    return V::new(tr, r, false);
                }
                V::new(tr, t, false)
            }
            (Repr::F32, Repr::F64) => {
                let t = self.t();
                self.line(&format!("{} = fpext float {} to double", t, v.v));
                V::new(tr, t, false)
            }
            _ => v,
        }
    }

    /// Converts a box between boxed static types; numeric widening inside requires a runtime call.
    fn widen_box(&mut self, b: V, from: &Type, to: &Type) -> V {
        let fnn = from.non_null();
        let tnn = to.non_null();
        let numeric_change = fnn != tnn && fnn.is_numeric() && (tnn.is_numeric());
        if numeric_change {
            let b = self.own(b);
            let ts = self.type_str(to);
            let r = self.call_val(Repr::Ptr, "l2_convert", &[b.typed(), format!("ptr {}", ts)]);
            self.release(&b);
            return V::new(Repr::Ptr, r, true);
        }
        b
    }

    fn compare(&mut self, op: CmpOp, a: V, at: &Type, b: V, bt: &Type) -> V {
        let t = self.t();
        if a.r == Repr::Ptr || b.r == Repr::Ptr || a.r == Repr::Void {
            let ab = self.to_box(a, at);
            let bb = self.to_box(b, bt);
            let c = self.call_val(Repr::I1, "l2_compare", &[format!("i8 {}", op.code()), ab.typed(), bb.typed()]);
            self.release(&ab);
            self.release(&bb);
            self.check();
            return V::new(Repr::I1, c, false);
        }
        if matches!(a.r, Repr::F32 | Repr::F64) {
            let pred = match op {
                CmpOp::Eq => "oeq",
                CmpOp::Ne => "une",
                CmpOp::Lt => "olt",
                CmpOp::Gt => "ogt",
                CmpOp::Le => "ole",
                CmpOp::Ge => "oge",
            };
            self.line(&format!("{} = fcmp {} {}, {}", t, pred, a.typed(), b.v));
        } else {
            let signed = matches!(at.deref(), Type::Int(i) if i.signed());
            let pred = match (op, signed) {
                (CmpOp::Eq, _) => "eq",
                (CmpOp::Ne, _) => "ne",
                (CmpOp::Lt, true) => "slt",
                (CmpOp::Gt, true) => "sgt",
                (CmpOp::Le, true) => "sle",
                (CmpOp::Ge, true) => "sge",
                (CmpOp::Lt, false) => "ult",
                (CmpOp::Gt, false) => "ugt",
                (CmpOp::Le, false) => "ule",
                (CmpOp::Ge, false) => "uge",
            };
            self.line(&format!("{} = icmp {} {}, {}", t, pred, a.typed(), b.v));
        }
        V::new(Repr::I1, t, false)
    }

    #[allow(clippy::too_many_arguments)]
    fn arith(&mut self, op: ArithOp, ty: &Type, a: V, at: &Type, b: V, bt: &Type, wrap: bool) -> V {
        let r = repr(ty);
        match r {
            Repr::Ptr => {
                let ab = self.to_box(a, at);
                let bb = self.to_box(b, bt);
                let res = self.call_val(Repr::Ptr, "l2_arith", &[format!("i8 {}", op.code()), ab.typed(), bb.typed(), format!("i1 zeroext {}", wrap)]);
                self.release(&ab);
                self.release(&bb);
                self.check();
                V::new(Repr::Ptr, res, true)
            }
            Repr::F32 | Repr::F64 => {
                let t = self.t();
                match op {
                    ArithOp::Pow => {
                        let name = if r == Repr::F32 { "llvm.pow.f32" } else { "llvm.pow.f64" };
                        self.m.intrinsics.insert(format!("declare {} @{}({}, {})", r.ll(), name, r.ll(), r.ll()));
                        self.line(&format!("{} = call {} @{}({}, {})", t, r.ll(), name, a.typed(), b.typed()));
                    }
                    _ => {
                        let ins = match op {
                            ArithOp::Add => "fadd",
                            ArithOp::Sub => "fsub",
                            ArithOp::Mul => "fmul",
                            ArithOp::Div => "fdiv",
                            _ => "frem",
                        };
                        self.line(&format!("{} = {} {}, {}", t, ins, a.typed(), b.v));
                    }
                }
                if float_kind(ty) == FloatTy::F16 {
                    let rr = self.call_val(Repr::F32, "l2_round_f16", &[format!("float {}", t)]);
                    return V::new(r, rr, false);
                }
                V::new(r, t, false)
            }
            _ => {
                let it = int_kind(ty);
                // shift amounts may have another width
                let b = if b.r != a.r {
                    let t = self.t();
                    let (wa, wb) = (int_width(a.r), int_width(b.r));
                    let opn = if wb > wa { "trunc" } else { "zext" };
                    self.line(&format!("{} = {} {} to {}", t, opn, b.typed(), a.r.ll()));
                    V::new(a.r, t, false)
                } else {
                    b
                };
                self.int_arith_op(op, it, a, b, wrap, false)
            }
        }
    }

    fn throw_block(&mut self, cond: &str, call: &str) {
        let (lt, lok) = (self.new_label("throw"), self.new_label("cont"));
        self.line(&format!("br i1 {}, label %{}, label %{}", cond, lt, lok));
        self.label_raw(&lt);
        self.line(call);
        let land = self.landing();
        self.br(&land);
        self.label_raw(&lok);
    }

    fn int_arith_op(&mut self, op: ArithOp, it: IntTy, a: V, b: V, wrap: bool, is_neg: bool) -> V {
        let r = a.r;
        let ll = r.ll();
        let s = it.signed();
        let opcode = if is_neg { 255 } else { op.code() };
        match op {
            ArithOp::Add | ArithOp::Sub | ArithOp::Mul => {
                let base = match op {
                    ArithOp::Add => "add",
                    ArithOp::Sub => "sub",
                    _ => "mul",
                };
                if wrap {
                    let t = self.t();
                    self.line(&format!("{} = {} {} {}, {}", t, base, ll, a.v, b.v));
                    return V::new(r, t, false);
                }
                let intr = format!("llvm.{}{}.with.overflow.{}", if s { "s" } else { "u" }, base, ll);
                self.m.intrinsics.insert(format!("declare {{{}, i1}} @{}({}, {})", ll, intr, ll, ll));
                let pair = self.t();
                self.line(&format!("{} = call {{{}, i1}} @{}({} {}, {} {})", pair, ll, intr, ll, a.v, ll, b.v));
                let v = self.t();
                self.line(&format!("{} = extractvalue {{{}, i1}} {}, 0", v, ll, pair));
                let ov = self.t();
                self.line(&format!("{} = extractvalue {{{}, i1}} {}, 1", ov, ll, pair));
                self.throw_block(&ov, &format!("call void @l2_throw_overflow(i8 {}, i8 {})", it.code(), opcode));
                V::new(r, v, false)
            }
            ArithOp::Div | ArithOp::Rem => {
                let is_rem = op == ArithOp::Rem;
                let z = self.t();
                self.line(&format!("{} = icmp eq {} {}, 0", z, ll, b.v));
                self.throw_block(&z, &format!("call void @l2_throw_div_zero(i1 zeroext {})", is_rem));
                if !s {
                    let t = self.t();
                    self.line(&format!("{} = {} {} {}, {}", t, if is_rem { "urem" } else { "udiv" }, ll, a.v, b.v));
                    return V::new(r, t, false);
                }
                let min = it.min();
                let (m1, mn) = (self.t(), self.t());
                self.line(&format!("{} = icmp eq {} {}, -1", m1, ll, b.v));
                self.line(&format!("{} = icmp eq {} {}, {}", mn, ll, a.v, min));
                let ov = self.t();
                self.line(&format!("{} = and i1 {}, {}", ov, m1, mn));
                if !wrap && !is_rem {
                    self.throw_block(&ov, &format!("call void @l2_throw_overflow(i8 {}, i8 {})", it.code(), opcode));
                }
                let safe = self.t();
                self.line(&format!("{} = select i1 {}, {} 1, {} {}", safe, ov, ll, ll, b.v));
                let q = self.t();
                self.line(&format!("{} = {} {} {}, {}", q, if is_rem { "srem" } else { "sdiv" }, ll, a.v, safe));
                let res = self.t();
                let special = if is_rem { "0".to_string() } else { min.to_string() };
                self.line(&format!("{} = select i1 {}, {} {}, {} {}", res, ov, ll, special, ll, q));
                V::new(r, res, false)
            }
            ArithOp::Pow => {
                let a64 = self.iext64(&a, s);
                let b64 = self.iext64(&b, s);
                let rv = self.call_val(Repr::I64, "l2_pow_int", &[format!("i8 {}", it.code()), format!("i64 {}", a64), format!("i64 {}", b64), format!("i1 zeroext {}", wrap)]);
                self.check();
                let t = self.itrunc(&rv, r);
                V::new(r, t, false)
            }
            ArithOp::BitAnd | ArithOp::BitOr | ArithOp::BitXor => {
                let ins = match op {
                    ArithOp::BitAnd => "and",
                    ArithOp::BitOr => "or",
                    _ => "xor",
                };
                let t = self.t();
                self.line(&format!("{} = {} {} {}, {}", t, ins, ll, a.v, b.v));
                V::new(r, t, false)
            }
            ArithOp::Shl | ArithOp::Shr => {
                let m = self.t();
                self.line(&format!("{} = and {} {}, {}", m, ll, b.v, it.bits() - 1));
                let ins = match (op, s) {
                    (ArithOp::Shl, _) => "shl",
                    (_, true) => "ashr",
                    _ => "lshr",
                };
                let t = self.t();
                self.line(&format!("{} = {} {} {}, {}", t, ins, ll, a.v, m));
                V::new(r, t, false)
            }
        }
    }
}

fn int_width(r: Repr) -> u32 {
    match r {
        Repr::I1 => 1,
        Repr::I8 => 8,
        Repr::I16 => 16,
        Repr::I32 => 32,
        _ => 64,
    }
}

#[allow(dead_code)]
fn builtin_id(b: Builtin) -> u16 {
    b as u16
}
